#!/bin/bash

battery_low=25
battery_level=$(acpi -b | cut -d, -f2 | cut --characters=2,3,4 | sed 's/%//g')
charging=$(acpi -b | grep -c "Charging")

if [ $battery_level -lt $battery_low ] && [ $charging -eq 0 ] 
then
	notify-send "🔋 Battery Low: ${battery_low}%" \
		"Plug into power source 🔌" -t 10000
fi
