#!/bin/sh

RSSFILE="$HOME/.newsboat/urls"

! echo "$1" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	notify-send "That doesn't look like a full URL." && exit
if awk '{print $1}' "$RSSFILE" | grep "^$1$" >/dev/null; then
	notify-send "You already have this RSS feed."
else
	echo "$1" >> "$RSSFILE" && notify-send "RSS feed added."
fi
